name: trendx
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  http: ^1.2.1
  webview_flutter: ^4.4.2
  html: ^0.15.4
  beautiful_soup_dart: ^0.3.0
  youtube_player_flutter: ^9.0.1
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  lucide_icons: any
  flutter_svg: ^2.0.10
  image_picker: ^1.0.7
  flutter_riverpod: ^3.2.0
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/appicon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/logo/appicon.png"
